[FEATURE] add DKVMN
bigdata-ustc/EduKTM pull request #24
Opened 2022-03-18 04:10 UTC by 0russwest0

## Description ##
add DKVMN

### What does this implement/fix? Explain your changes.
add DKVMN

#### Pull request type
- [ ] [DATASET] Add a new dataset
- [ ] [BUGFIX] Bugfix
- [x] [FEATURE] New feature (non-breaking change which adds functionality)
- [ ] [BREAKING] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] [STYLE] Code style update (formatting, renaming)
- [ ] [REFACTOR] Refactoring (no functional changes, no api changes)
- [ ] [BUILD] Build related changes
- [ ] [DOC] Documentation content changes
- [ ] [Sync] Synchronization with a repository 
- [ ] [OTHER] Other (please describe): 

#### Changes
add DKVMN

### Does this close any currently open issues?
no

### Any relevant logs, error output, etc?
no

## Checklist ##
Before you submit a pull request, please make sure you have to following:

### Essentials ###
- [x] PR's title starts with a category (e.g. [BUGFIX], [FEATURE], [BREAKING], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [x] All changes have test coverage and al tests passing
- [x] Code is well-documented (extended the README / documentation, if necessary)
- [x] If this PR is your first one, add your name and github account to [AUTHORS.md](../blob/master/AUTHORS.md)

## Comments ##
- If this change is a backward incompatible change, why must this change be made.
- Interesting edge cases to note here

2022-03-18 08:42 UTC, fannazya approved these changes

2022-03-18 08:43 UTC, fannazya approved these changes

2022-03-18 09:03 UTC, fannazya requested changes
Please add an example.

2022-04-25 13:58 UTC, tswsxk requested changes
The annotations of each function are expected to be strictly follow numpy-style.

2022-04-25 13:59 UTC, tswsxk commented
@fannazya why I do not see any feedback from you since last month?

2022-04-26 02:27 UTC, tswsxk requested changes

2022-04-26 02:27 UTC, tswsxk commented on examples/DKVMN/DKVMN.py
> +from load_data import DATA
DATA is a constant-style name, use Data if needed

2022-04-26 02:27 UTC, tswsxk commented on examples/DKVMN/load_data.py
> +                        endINdex  = len(A)
variable name should be UnderScoreCase rather than CamelCase

2022-05-18 02:30 UTC, tswsxk approved these changes

2022-05-18 03:51 UTC, tswsxk approved these changes

2022-05-18 06:07 UTC, merged